spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: z123456w
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    password: guest
    username: guest
  redis:
    host: 192.168.99.100
    port: 6379
    password: mypassword
  jpa:
    show-sql: true
PRODUT:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env: test4
girl:
  name: lili
  age: 21
