spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: z123456w
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
  redis:
    host: 127.0.0.1
    port: 6379
env: test13
girl:
  name: lili
  age: 21
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
# 暴露actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
